{
 "title": "nebula",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "storage副本数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(nebula_graphd_storageClient_error_qps_avg_3600{kubernetes_namespace=\"nebula-monitor\"})"
    }
   ]
  },
  {
   "title": "graphd副本数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(nebula_graphd_storageClient_error_qps_avg_3600{kubernetes_namespace=\"nebula-monitor\"})"
    }
   ]
  },
  {
   "title": "metad副本数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nebula_metad_heartbeat_latency_count_3600{kubernetes_namespace=\"NEBULA_NAMESPACE\"})"
    }
   ]
  },
  {
   "title": "memory利用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{name=~\"k8s_POD_nebula-graphd-.*|k8s_POD_nebula-metad-.*|k8s_POD_nebula-storaged-.*\",namespace=\"NEBULA_NAMESPACE\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "cpu利用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{name=~\"k8s_nebula-graphd.*|k8s_nebula-metad.*|k8s_nebula-storaged.*\", namespace=\"NEBULA_NAMESPACE\"}[2m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "网络吞吐",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{name=~\"k8s_POD_nebula-graphd.*|k8s_POD_nebula-metad.*|k8s_POD_nebula-storaged.*\", namespace=\"NEBULA_NAMESPACE\"}[2m])) by (name)",
     "legendFormat": "->{{name}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{name=~\"k8s_POD_nebula-graphd.*|k8s_POD_nebula-metad.*|k8s_POD_nebula-storaged.*\", namespace=\"NEBULA_NAMESPACE\"}[2m])) by (name)",
     "legendFormat": "<-{{name}}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\"k8s_POD_nebula-graphd.*|k8s_POD_nebula-metad.*|k8s_POD_nebula-storaged.*\",namespace=\"NEBULA_NAMESPACE\"}[2m])",
     "legendFormat": "Recived"
    },
    {
     "expr": "- rate (container_network_transmit_bytes_total{name=~\"k8s_POD_nebula-graphd.*|k8s_POD_nebula-metad.*|k8s_POD_nebula-storaged.*\",namespace=\"NEBULA_NAMESPACE\"}[2m])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "GO执行个数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_go_latency_count_60{namespace=\"NEBULA_NAMESPACE\"}"
    }
   ]
  },
  {
   "title": "Insert Edge个数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_edge_latency_count_60{kubernetes_namespace=\"NEBULA_NAMESPACE\"}"
    }
   ]
  },
  {
   "title": "Insert Vertex个数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_vertex_latency_count_60{kubernetes_namespace=\"NEBULA_NAMESPACE\"}"
    }
   ]
  },
  {
   "title": "Insert Edges Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_edge_latency_avg_60{kubernetes_namespace=\"NEBULA_NAMESPACE\"}"
    }
   ]
  },
  {
   "title": "Go Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_go_latency_avg_60{kubernetes_namespace=\"NEBULA_NAMESPACE\"}"
    }
   ]
  },
  {
   "title": "Go QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_go_qps_avg_60{kubernetes_namespace=\"NEBULA_NAMESPACE\"}"
    }
   ]
  },
  {
   "title": "Insert Vertex Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_vertex_latency_avg_60{kubernetes_namespace=\"NEBULA_NAMESPACE\"}"
    }
   ]
  },
  {
   "title": "Insert Vertex QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_vertex_qps_avg_60{kubernetes_namespace=\"NEBULA_NAMESPACE\"}"
    }
   ]
  },
  {
   "title": "Insert Edge QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_edge_qps_avg_60{kubernetes_namespace=\"NEBULA_NAMESPACE\"}"
    }
   ]
  },
  {
   "title": "磁盘使用情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{namespace=\"NEBULA_NAMESPACE\",device=\"/dev/vda1\",name=~\"k8s_POD_nebula-metad.*|k8s_POD_nebula-storaged.*\"}"
    }
   ]
  }
 ]
}